config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :reviews, only:[:new, :create]
  resources :trucks, only: [:index, :show]
  resources :users, only:[:show, :edit, :update, :destroy]
  resources :favorites, only:[:create, :destroy]
  get '/signup', to: 'users#new', as: 'signup'
  get "/signin", to: "sessions#new", as: "signin"
  post "/sessions", to: "sessions#create", as: "sessions"
  delete "/sessions", to: "sessions#destroy", as: "signout"
  post "/signup", to: 'users#create', as: "users"
  get "/analytics", to: "sessions#index", as: "analytics"
  root "sessions#new"

end

app/models/truck.rb
class Truck < ApplicationRecord
  has_many :reviews
  has_many :items
  has_many :favorites
  has_many :users, through: :favorites
  has_many :schedules
  belongs_to :category
  belongs_to :location


  def rating
    if self.reviews.empty?
      nil
    else
      self.reviews.average(:rating).round(1)
    end
  end

  def self.favorite
    max_count = Truck.all.max_by{|truck| truck.users.count}.users.count
    trucks = Truck.all.select{|truck| truck.users.count == max_count}
    truck_names = trucks.collect{|truck| truck.name}.to_sentence
    has_have = trucks.count > 1 ? "have" : "has"
    it_them = trucks.count > 1 ? "them" : "it"
    "#{truck_names} #{has_have} been saved to favorites by the most users, with #{max_count} users having favorited #{it_them}!"
  end

  def self.zip_with_most_trucks
    #only returns first zip even if tied
    zips_array = Truck.all.collect{|tr| tr.location.zip}
    zips_hash = zips_array.inject(Hash.new(0)){|zip_codes, zip| zip_codes[zip] += 1; zip_codes}
    max_value = zips_hash.max_by{|k,v| v}
    max_key = zips_hash.key(max_value)
    "#{max_key} has the most foodtrucks with #{max_value} trucks!"
  end

  def self.highest_rated
    max_rating = Truck.all.max_by{|truck| truck.rating ? truck.rating : 0}.rating
    trucks = Truck.all.select{|truck| truck.rating == max_rating}
    truck_names = trucks.collect{|truck| truck.name}.to_sentence
    has_have = trucks.count > 1 ? "have" : "has"
    "#{truck_names} #{has_have} been rated highest by our users, with a rating of #{max_rating}!"
  end

  def pricey
    if self.items.empty?
      nil
    else
      avg = self.items.average(:price)

      if avg < 6
        1
      elsif avg < 10
        2
      elsif avg < 14
        3
      else
        4
      end
    end
  end

  def self.trucks_by_zip(zip)
    if zip
      Truck.all.select{|tr| tr.location.zip == zip}
    else
      Truck.all
    end
  end


  def self.url_generator(zip)
    # @trucks = Truck.all.select{|tr| tr.location.zip == zip}
    @trucks = self.trucks_by_zip(zip)
    key = "AIzaSyBcQBWJhUdprvVfhh4CAmwY7ixtNbaQGvc"
    url = <<-URL
      https://maps.googleapis.com/maps/api/staticmap?center=#{zip}&zoom=14&size=3000x300&maptype=roadmap&key=#{key}
    URL

    @trucks.each_with_index do |tr, i|
      address = tr.location.street_address.gsub(/ /, '+') + ',' + tr.location.city.gsub(/ /, '+')  + ',' + tr.location.state.gsub(/ /, '+')
      url += "&markers=color:red%7Clabel:#{i+1}%7C#{address}"
    end
    url.gsub(/[\s]+/,'')
  end

end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController

  def index
    @user = current_user
    @trucks = Truck.trucks_by_zip(params[:zip])
    if params[:zip]
      @url = Truck.url_generator(params[:zip])
    end
    # if !params[:zip]
    #   @trucks = Truck.all
    # else
    #   @url = Truck.url_generator(params[:zip])
    #   @trucks = Truck.all.select{|tr| tr.location.zip == params[:zip]}
    # end
  end

  # def new
  # end
  #
  # def create
  # end

  def show
    # need to add some sort of location thingy to show page
    @truck = Truck.find(params[:id])
    session[:truck] = @truck.id
  end

  # def edit
  # end
  #
  # def update
  # end

end

app/views/trucks/index.html.erb
<%# search bar%>
<hgroup class="row">
  <h2>Search Food Trucks By Zip Code</h2>
</hgroup>


<form class="navbar-form navbar-left" role="search" action="/trucks" method='get' >
    <div class="form-group">
        <input name="zip" type="text" class="form-control" placeholder="Zip Code">
    </div>
    <button type="submit" class="btn btn-default">
        <span class="glyphicon glyphicon-search"></span>
    </button>
</form>

<br>
<br>
<br>

<%# search results header%>
<%# url is blank where no search was run yet%>
<% if @url %>
  <hgroup class="row">
  		<h2 class="lead"><%= @trucks.count %> food trucks were found in your area</h2>
  </hgroup>

  <div class="col-l-12 img-fluid" style="text-align: center;">
        <img src=<%= @url %> alt="">
  </div>
<% end %>

<%# map - only shows after search - otherise url is nil %>


<br>
<br>

<%# each truck details %>
<div class="row row-margin-bottom">

  <% @trucks.each_with_index do |tr, i| %>
    <div class="col-md-5 no-padding lib-item" data-category="view">
        <div class="lib-panel">
            <div class="row box-shadow">
                <div class="col-md-6">
                    <a href="<%= truck_path(tr) %>"><img class="lib-img-show" src="<%= "#{tr.img_url}" %>" height="160" width="200"></a>
                </div>
                <div class="col-md-6">
                    <div class="lib-row lib-header">
                        <h5><%= "#{i+1}. " %><%= link_to tr.name, truck_path(tr) %></span></h5>
                        <div class="lib-header-seperator"></div>
                    </div>
                    <div class="lib-row lib-desc">
                      <%= tr.location.street_address %><br>
                      <%= tr.category.name %><br>

                      <%# rating %>
                      <% if tr.rating %>
                        <%= tr.rating %>
                        -
                        <% tr.rating.round.times do %>
                          <span class="glyphicon glyphicon-star"></span>
                        <% end %>
                        <% (5 - tr.rating.round).times do %>
                          <span class="glyphicon glyphicon-star-empty"></span>
                        <% end %><br>
                      <% end %>

                      <%# pricey %>
                      <% if tr.pricey %>
                        <% tr.pricey.times do %>
                          <span class="glyphicon glyphicon-bitcoin"></span>
                        <% end %>
                      <% end %>

                    </div>
                </div>
            </div>
        </div>
    </div>
  <% end %>
</div>

app/views/trucks/show.html.erb
<%# really have no idea why, but this div encloses everything from top until menu. and it seems to be doing something right so I'll keep it %>
<div class="">
  <%# heading %>
  <h1><%= @truck.name %></h1>
  <h3><%= @truck.category.name %></h3>

  <%# display rating %>
  <% if @truck.rating %>
    <h3 class="rating-num">
      <%= @truck.rating %> -
      <% @truck.rating.round.times do %>
        <span class="glyphicon glyphicon-star"></span>
      <% end %>
      <% (5 - @truck.rating.round).times do %>
        <span class="glyphicon glyphicon-star-empty"></span>
      <% end %>
    </h3><br>
  <% end %>

  <% if @truck.pricey %>
    <% @truck.pricey.times do %>
      <span class="glyphicon glyphicon-bitcoin"></span>
    <% end %>
  <% end %>

  <h1>

  </h1>

  <br>
  <%# This row includes favorite and review buttons %>
  <div class="row">
    <%# Review Button %>
    <% if !Review.find_by(user_id: current_user.id, truck_id: @truck.id) %>
      <div class="button col-md-2">
          <form method="get" action="/reviews/new" >
            <button type="submit" class="theme-background white btn-lg btn">
              <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Write A Review
            </button>
          </form>
      </div>
    <% end %>
    <%# favorite/unfavorite buttton %>
    <div class="col-md-1">
      <% if Favorite.find_by(user_id: current_user.id, truck_id: @truck.id) %>
        <%= form_tag favorite_path(@truck), method: 'delete' do %>
        <button type="submit" class="theme-background white btn-lg btn">
          <span class="glyphicon glyphicon-star" aria-hidden="true"></span> Unfavorite
        </button>
          <% end %>
      <% else %>
      <%= form_tag favorites_path do %>
        <button type="submit" class="theme-background white btn-lg btn">
          <span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span> Favorite
        </button>
        <% end %>
      <% end %>
    </div>

  </div><%# end buttons div %>

  <br>

  <%# large truck img %>
  <div class="" style='text-align: center;'>
    <img src="<%= "#{@truck.img_url}" %>" alt="" style="width:900px;height:500px;">
  </div>

  <br>
  <br>

  <h3><%= @truck.description %></h3>

</div>

<br>

<%# Menu %>

<h3>Menu:</h3>
<br>
<div class="table">
    <table style="width:40%; align:center" class ="table table-striped">
        <tr>
          <th align="left">Menu items</th>
          <th align="left">Price</th>
        </tr>
      <% @truck.items.each do |item| %>
        <tr>
          <td><%= item.name %></td>
          <td>$<%= item.price %></td>
        </tr>
      <% end %>
    </table>
</div>

<br>
<br>
<br>
<br>

<%# Show all Reviews %>
<div class="">
  <% if @truck.reviews.empty? %>

    <h4>No reviews yet. Be the first to write a review!</h4>

  <% else %>

    <div class="" style="text-align: center;"><h2>Reviews</h2></div>
    <% @truck.reviews.each do |review| %>
        <div class="reviews">
          <div class="row blockquote review-item">
            <div class="col-md-3 text-center">
              <img class="rounded-circle reviewer" src="http://standaloneinstaller.com/upload/avatar.png">
              <div class="caption">
                <small>by <a href="#joe"><%= review.user.username %></a></small>
              </div>

            </div>
            <div class="col-md-9">
              <h4><%= review.title %></h4>
              <div class="ratebox text-center" data-id="0" data-rating="5"></div>
              <p class="review-text"><%= review.content %></p>
            </div>
          </div>
        </div>
    <% end %>
  <% end %>

</div>