config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :reviews, only:[:new, :create]
  resources :trucks, only: [:index, :show]
  resources :users, only:[:show, :edit, :update, :destroy]
  resources :favorites, only:[:create, :destroy]
  get '/signup', to: 'users#new', as: 'signup'
  get "/signin", to: "sessions#new", as: "signin"
  post "/sessions", to: "sessions#create", as: "sessions"
  delete "/sessions", to: "sessions#destroy", as: "signout"
  post "/signup", to: 'users#create', as: "users"
  get "/analytics", to: "sessions#index", as: "analytics"
  root "sessions#new"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodTruckTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Compiled and minified CSS -->
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css"> -->

    <!-- Compiled and minified JavaScript -->
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script> -->

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="../../assets/stylesheets/application.css">

  </head>

  <body style="background-color: #e3f3f9;">

    <nav class="navbar navbar-light navbar-static-top" style="background-color: #8e2222">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Food Truck Tracker</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav">
            <% if logged_in? %>
              <li>
                <a data-method="delete" href=<%="#{signout_path}"%>><span class="glyphicon glyphicon-log-out"></span> Sign Out</a>
              </li>

              <li>
                <a href=<%="#{user_path(session[:user_id])}"%>><span class="glyphicon glyphicon-user"></span> My Profile</a>
              </li>

              <li>
                <a href=<%="#{trucks_path}"%>><span class="glyphicon glyphicon-search"></span> Search Food Trucks</a>
              </li>
              <!-- <li><%= link_to "My Profile", user_path(session[:user_id]), method: :get %></li> -->
              <!-- <li><%= link_to "Search Foodtrucks", trucks_path %></li> -->
            <% else %>
              <li>
                <a href=<%="#{signin_path}"%>><span class="glyphicon glyphicon-log-in"></span> Sign In</a>
              </li>

              <li>
                <a href=<%="#{signup_path}"%>><span class="glyphicon glyphicon-user"></span> Sign Up</a>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <div class="row vertical-offset-100">
        <div class="col-md-6 col-md-offset-3">
          <div class="error-div">
              <% flash.each do |key, value| %>
                <em><%= value %></em>
              <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <%= yield %>
    </div>

    <!-- Compiled and minified JavaScript -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

  </body>
</html>